services:
  app:
    build: .
    container_name: chores-rewards-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - web

networks:
  web:
    external: true
