services:
  app:
    build: .
    container_name: chores-rewards-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
    networks:
      - web

networks:
  web:
    external: true
