# Docker Compose for Chores & Rewards PWA
version: '3.8'

services:
  chores-app:
    build: .
    container_name: chores-rewards-app
    ports:
      - "3000:5000"  # Map host port 3000 to container port 5000
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      # Optional: Mount a volume for persistent logs
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s