# Traefik configuration for multiple websites
api:
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      tlsChallenge: {}
      email: rod.lunt@me.com
      storage: acme.json