name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test-connection:
    name: Test SSH to Server
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            echo "✅ SSH Connection Successful!"
            echo "Server: $(hostname)"
            echo "User: $(whoami)"
            echo "Current directory: $(pwd)"
            echo ""
            echo "Checking deployment path..."
            if [ -d "${{ secrets.DEPLOY_PATH }}" ]; then
              echo "✅ Deploy path exists: ${{ secrets.DEPLOY_PATH }}"
              cd ${{ secrets.DEPLOY_PATH }}
              echo "Contents:"
              ls -la
            else
              echo "❌ Deploy path NOT found: ${{ secrets.DEPLOY_PATH }}"
            fi
            echo ""
            echo "Checking Docker..."
            if command -v docker &> /dev/null; then
              echo "✅ Docker is installed"
              docker --version
            else
              echo "❌ Docker NOT found"
            fi
            echo ""
            echo "Checking Docker Compose..."
            if command -v docker-compose &> /dev/null; then
              echo "✅ Docker Compose is installed"
              docker-compose --version
            else
              echo "❌ Docker Compose NOT found"
            fi
